name: Publish to GitHub Packages
on:
  release:
    types: [published]

jobs:
  publish-to-nuget:
    name: Publish release to GitHub Packages
    uses: markwhitaker/shared-workflows/.github/workflows/gradle-publish-to-github-packages.yml@main
    secrets: inherit
